###Recuperar todos los citys
GET http://localhost:3000/api/city


###Crear un city
# @name createCity
POST http://localhost:3000/api/city
Content-Type: application/json

{
    "city_name": "CABA",
    "province": "Buenos Aires",
    "zip_code": 3000
}

###ID
@id = {{createCity.response.body.data.id}}
###Recuperar un city por id
GET http://localhost:3000/api/city/1


###Actualizar un city
PATCH http://localhost:3000/api/city/{{id}}
Content-Type: application/json

{
    "SQL INJECTIN": "DROP TABLE city",
    "city_name": "Rafaela"
}


###Eliminar un city
DELETE http://localhost:3000/api/city/{{id}}
