###Recuperar todos los locationos
GET http://localhost:3000/api/location


###Crear un location
# @name createLocation
POST http://localhost:3000/api/location
Content-Type: application/json

{
    "location_name": "sala de las artes",
    "address": "ovlagos 246",
    "city": "rosario",
    "state": "santa fe",
    "zip": 3000
}

###ID
@id = {{createLocation.response.body.data.id}}
###Recuperar un location por id
GET http://localhost:3000/api/location/{{id}}


###Actualizar un location
PATCH http://localhost:3000/api/location/{{id}}
Content-Type: application/json

{
    "SQL INJECTIN": "DROP TABLE location",
    "location_name": "centro cultural guemes"
}


###Eliminar un location
DELETE http://localhost:3000/api/location/{{id}}
