###Recuperar todos los locationos
GET http://localhost:3000/api/location


###Crear un location
# @name createLocation
POST http://localhost:3000/api/location
Content-Type: application/json

{
    "location_name": "costanera cultural",
    "address": "corrientes 543",
    "max_capacity": 1000,
    "city": 1
}

###ID
@id = {{createLocation.response.body.data.id}}
###Recuperar un location por id
GET http://localhost:3000/api/location/1


###Actualizar un location
PATCH http://localhost:3000/api/location/{{id}}
Content-Type: application/json

{
    "SQL INJECTIN": "DROP TABLE location",
    "location_name": "centro cultural guemes",
    "max_capacity": 2000
}


###Eliminar un location
DELETE http://localhost:3000/api/location/{{id}}
