###Recuperar todos los ticketTypeos
GET http://localhost:3000/api/ticketType


###Crear un ticketType
# @name createTicketType
POST http://localhost:3000/api/ticketType
Content-Type: application/json

{
    "ticketType_name": "sala de las artes",
    "begin_datetime": "2021-10-10 20:00:00",
    "finish_datetime": "2021-10-30 23:00:00",
    "price": 1000,
    "max_quantity":100,
    "event": 1
}

###ID
@id = {{createTicketType.response.body.data.id}}
###Recuperar un ticketType por id
GET http://localhost:3000/api/ticketType/{{id}}


###Actualizar un ticketType
PATCH http://localhost:3000/api/ticketType/{{id}}
Content-Type: application/json

{
    "SQL INJECTIN": "DROP TABLE ticketType",
    "ticketType_name": "preventa 01"
}


###Eliminar un ticketType
DELETE http://localhost:3000/api/ticketType/{{id}}
